name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Run tests
      run: bun test
      env:
        DATABASE_URL: postgres://test_user:test_password@localhost:5433/test_db 